spring:
    redis:
        database: 0
        host: localhost
        port: 6379
        timeout: 6000ms
        jedis:
          pool:
            max-active: 200
            max-wait: -1ms
            max-idle: 10
            min-idle: 0
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    cloud:
        bus:
           enabled: true
               trace:
                   enabled: true
management:
    endpoints:
        web:
            exposure:
                include: "*"